name: si_env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.9.0=pyh29332c3_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py311he736701_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - brotli-python=1.1.0=py311hda3d55a_2
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.4.26=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py311he736701_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py311h3257749_0
  - cpython=3.11.12=py311hd8ed1ab_0
  - crc32c=2.7.1=py311he736701_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.14=py311hda3d55a_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.57.0=py311h5082efb_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=h57928b3_1
  - glib=2.84.1=h3d4babf_0
  - glib-tools=2.84.1=h4394cf3_0
  - graphite2=1.3.13=h63175ca_1003
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py311hc74fd12_101
  - harfbuzz=11.1.0=h8796e6f_0
  - hdbscan=0.8.39=py311h0a17f05_0
  - hdf5=1.14.6=nompi_hd5d9e70_101
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipympl=0.9.7=pyhd8ed1ab_1
  - ipython=9.2.0=pyhca29cf9_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.0=pyhd8ed1ab_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h1ea47a8_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh5737063_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kiwisolver=1.4.7=py311h3257749_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.3=h63175ca_0
  - libblas=3.9.0=31_h641d27c_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=31_h5e41251_mkl
  - libclang13=20.1.4=default_h6e92b77_0
  - libcurl=8.13.0=h88aaa65_0
  - libdeflate=1.23=h76ddb4d_0
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=14.2.0=h1383e82_2
  - libglib=2.84.1=h7025463_0
  - libgomp=14.2.0=h1383e82_2
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=31_h1aa476e_mkl
  - liblzma=5.8.1=h2466b09_1
  - libogg=1.3.5=h2466b09_1
  - libpng=1.6.47=h7a4582a_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.49.1=h67fdade_2
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.0=h797046b_4
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.7=h442d1da_1
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_2
  - llvmlite=0.44.0=py311h7deaa30_1
  - loky=3.5.3=pyhd8ed1ab_0
  - markupsafe=3.0.2=py311h5082efb_1
  - matplotlib=3.10.1=py311h1ea47a8_0
  - matplotlib-base=3.10.1=py311h8f1b1e4_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - mkl=2024.2.2=h66d3029_15
  - msgpack-python=1.1.0=py311h3257749_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - notebook=7.4.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.61.2=py311h0673bce_0
  - numcodecs=0.15.1=py311hcf9f919_0
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.5.0=ha4e3fda_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py311hcf9f919_3
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.44=h99c9b8b_2
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py311h43e43bb_0
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.0=had0cd8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=pyh29332c3_0
  - ply=3.11=pyhd8ed1ab_3
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - prompt_toolkit=3.0.51=hd8ed1ab_0
  - psutil=7.0.0=py311he736701_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyhab904b8_2
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyqt=5.15.10=py311h2d05f59_1
  - pyqt5-sip=12.13.0=py311hda3d55a_1
  - pyqtgraph=0.13.7=pyhd8ed1ab_1
  - pyside6=6.9.0=py311h9f82be6_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.12=h3f84c4b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=7_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=307=py311hda3d55a_3
  - pywinpty=2.0.15=py311hda3d55a_0
  - pyyaml=6.0.2=py311h5082efb_2
  - pyzmq=26.4.0=py311h484c95c_0
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.15=h9151539_3
  - qt6-main=6.9.0=h83cda92_1
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.24.0=py311ha250665_0
  - scikit-learn=1.6.1=py311hdcb8d17_0
  - scipy=1.15.2=py311h99d06ae_0
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.1.0=pyhff2d567_0
  - sip=6.8.6=py311hda3d55a_2
  - six=1.17.0=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.6=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.13.0=h62715c5_1
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py311he736701_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=16.0.0=py311he736701_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.4.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_26
  - vc14_runtime=14.42.34438=hfd919c2_26
  - vs2015_runtime=14.42.34438=h7142326_26
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=1.17.2=py311he736701_0
  - xarray=2025.4.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py311he736701_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - asciitree==0.3.3
      - click==8.1.8
      - cuda-bindings==12.9.0
      - cuda-python==12.9.0
      - distinctipy==1.3.4
      - docker==7.1.0
      - elephant==1.1.1
      - ephyviewer==1.7.0
      - et-xmlfile==2.0.0
      - faiss-cpu==1.11.0
      - fasteners==0.19
      - figurl==0.3.0a1
      - filelock==3.18.0
      - fsspec==2025.3.2
      - hdmf==4.0.0
      - huggingface-hub==0.30.2
      - kachery==2.0.2
      - kilosort==4.1.2
      - lazy-ops==0.2.0
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - mearec==1.9.2
      - meautility==1.5.2
      - mpmath==1.3.0
      - narwhals==1.38.0
      - neo==0.14.3
      - numpy==1.26.4
      - openpyxl==3.1.5
      - probeinterface==0.3.1
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pynapple==0.10.2
      - pynwb==3.0.0
      - quantities==0.16.2
      - rich==14.2.0
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - seaborn==0.13.2
      - simplejson==3.20.1
      - skops==0.11.0
      - sortingview==0.14.1
      - spikeinterface==0.103.2
      - spikeinterface-gui==0.10.0
      - spython==0.3.14
      - sympy==1.14.0
      - tabulate==0.9.0
      - torch==2.7.0+cu118
      - tridesclous==1.6.8
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - zarr==2.18.7
prefix: C:\Users\assad\miniconda3\envs\si_env
